AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false
