AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Exclude:
    - 'config/initializers/money.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  Enabled: false
